spring:
  application:
    name: Complaint System
  datasource:
    url: ${URL_DB_POSTGRES}
    username: ${USERNAME_DB_POSTGRES}
    password: ${PASSWORD_DB_POSTGRES}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: smtp-relay.brevo.com
#    port: 587
#    username: ${USERNAME_BREVO}
#    password: ${API_KEY2_BREVO}
#    properties:
#      mail:
#        smtp:
#          auth: true


#  sendgrid:
#    api-key: ${API_KEY_SENDGRID}
#    from:
#      email: ${EMAIL_SENDGRID}
#File Storage Configuration
file:
  upload-dir: ./uploads/evidence

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000



